# Generated by Django 5.0.5 on 2024-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='default-pic.jpg', upload_to='menu_pictures'),
        ),
    ]
